export class IMultiOption
{
    id:number;
    Name:String;
}

export class MultiOption
{
    id:string;
    Name:string;
}
export const MockMultiOptionuniqueID:MultiOption[]=[
    {id:'1',Name:'Adhar Number'},
    {id:'2',Name:'Voter Number'},
    {id:'3',Name:'PAN Number'},
    {id:'4',Name:'DL Number'},
    {id:'5',Name:'Other Number'}
]

export const MockMultiOptionAddressType:MultiOption[]=[
    {id:'1',Name:'Primary'},
    {id:'2',Name:'Secoundary'},
    {id:'3',Name:'Billing'},
    {id:'4',Name:'Home'},
    {id:'5',Name:'contact'}
]

export const MockMultiOptionUserList:MultiOption[]=[
        {Name: "Afghanistan", id: "AF"},
        {Name: "Åland Islands", id: "AX"},
        {Name: "Albania", id: "AL"},
        {Name: "Algeria", id: "DZ"},
        {Name: "American Samoa", id: "AS"},
        {Name: "AndorrA", id: "AD"},
        {Name: "Angola", id: "AO"},
        {Name: "Anguilla", id: "AI"},
        {Name: "Antarctica", id: "AQ"},
        {Name: "Antigua and Barbuda", id: "AG"},
        {Name: "Argentina", id: "AR"},
        {Name: "Armenia", id: "AM"},
        {Name: "Aruba", id: "AW"},
        {Name: "Australia", id: "AU"},
        {Name: "Austria", id: "AT"},
        {Name: "Azerbaijan", id: "AZ"},
        {Name: "Bahamas", id: "BS"},
        {Name: "Bahrain", id: "BH"},
        {Name: "Bangladesh", id: "BD"},
        {Name: "Barbados", id: "BB"},
        {Name: "Belarus", id: "BY"},
        {Name: "Belgium", id: "BE"},
        {Name: "Belize", id: "BZ"},
        {Name: "Benin", id: "BJ"},
        {Name: "Bermuda", id: "BM"},
        {Name: "Bhutan", id: "BT"},
        {Name: "Bolivia", id: "BO"},
        {Name: "Bosnia and Herzegovina", id: "BA"},
        {Name: "Botswana", id: "BW"},
        {Name: "Bouvet Island", id: "BV"},
        {Name: "Brazil", id: "BR"},
        {Name: "British Indian Ocean Territory", id: "IO"},
        {Name: "Brunei Darussalam", id: "BN"},
        {Name: "Bulgaria", id: "BG"},
        {Name: "Burkina Faso", id: "BF"},
        {Name: "Burundi", id: "BI"},
        {Name: "Cambodia", id: "KH"},
        {Name: "Cameroon", id: "CM"},
        {Name: "Canada", id: "CA"},
        {Name: "Cape Verde", id: "CV"},
        {Name: "Cayman Islands", id: "KY"},
        {Name: "Central African Republic", id: "CF"},
        {Name: "Chad", id: "TD"},
        {Name: "Chile", id: "CL"},
        {Name: "China", id: "CN"},
        {Name: "Christmas Island", id: "CX"},
        {Name: "Cocos (Keeling) Islands", id: "CC"},
        {Name: "Colombia", id: "CO"},
        {Name: "Comoros", id: "KM"},
        {Name: "Congo", id: "CG"},
        {Name: "Congo, The Democratic Republic of the", id: "CD"},
        {Name: "Cook Islands", id: "CK"},
        {Name: "Costa Rica", id: "CR"},
        {Name: "Cote D'Ivoire", id: "CI"},
        {Name: "Croatia", id: "HR"},
        {Name: "Cuba", id: "CU"},
        {Name: "Cyprus", id: "CY"},
        {Name: "Czech Republic", id: "CZ"},
        {Name: "Denmark", id: "DK"},
        {Name: "Djibouti", id: "DJ"},
        {Name: "Dominica", id: "DM"},
        {Name: "Dominican Republic", id: "DO"},
        {Name: "Ecuador", id: "EC"},
        {Name: "Egypt", id: "EG"},
        {Name: "El Salvador", id: "SV"},
        {Name: "Equatorial Guinea", id: "GQ"},
        {Name: "Eritrea", id: "ER"},
        {Name: "Estonia", id: "EE"},
        {Name: "Ethiopia", id: "ET"},
        {Name: "Falkland Islands (Malvinas)", id: "FK"},
        {Name: "Faroe Islands", id: "FO"},
        {Name: "Fiji", id: "FJ"},
        {Name: "Finland", id: "FI"},
        {Name: "France", id: "FR"},
        {Name: "French Guiana", id: "GF"},
        {Name: "French Polynesia", id: "PF"},
        {Name: "French Southern Territories", id: "TF"},
        {Name: "Gabon", id: "GA"},
        {Name: "Gambia", id: "GM"},
        {Name: "Georgia", id: "GE"},
        {Name: "Germany", id: "DE"},
        {Name: "Ghana", id: "GH"},
        {Name: "Gibraltar", id: "GI"},
        {Name: "Greece", id: "GR"},
        {Name: "Greenland", id: "GL"},
        {Name: "Grenada", id: "GD"},
        {Name: "Guadeloupe", id: "GP"},
        {Name: "Guam", id: "GU"},
        {Name: "Guatemala", id: "GT"},
        {Name: "Guernsey", id: "GG"},
        {Name: "Guinea", id: "GN"},
        {Name: "Guinea-Bissau", id: "GW"},
        {Name: "Guyana", id: "GY"},
        {Name: "Haiti", id: "HT"},
        {Name: "Heard Island and Mcdonald Islands", id: "HM"},
        {Name: "Holy See (Vatican City State)", id: "VA"},
        {Name: "Honduras", id: "HN"},
        {Name: "Hong Kong", id: "HK"},
        {Name: "Hungary", id: "HU"},
        {Name: "Iceland", id: "IS"},
        {Name: "India", id: "IN"},
        {Name: "Indonesia", id: "ID"},
        {Name: "Iran, Islamic Republic Of", id: "IR"},
        {Name: "Iraq", id: "IQ"},
        {Name: "Ireland", id: "IE"},
        {Name: "Isle of Man", id: "IM"},
        {Name: "Israel", id: "IL"},
        {Name: "Italy", id: "IT"},
        {Name: "Jamaica", id: "JM"},
        {Name: "Japan", id: "JP"},
        {Name: "Jersey", id: "JE"},
        {Name: "Jordan", id: "JO"},
        {Name: "Kazakhstan", id: "KZ"},
        {Name: "Kenya", id: "KE"},
        {Name: "Kiribati", id: "KI"},
        {Name: "Korea, Democratic People'S Republic of", id: "KP"},
        {Name: "Korea, Republic of", id: "KR"},
        {Name: "Kuwait", id: "KW"},
        {Name: "Kyrgyzstan", id: "KG"},
        {Name: "Lao People'S Democratic Republic", id: "LA"},
        {Name: "Latvia", id: "LV"},
        {Name: "Lebanon", id: "LB"},
        {Name: "Lesotho", id: "LS"},
        {Name: "Liberia", id: "LR"},
        {Name: "Libyan Arab Jamahiriya", id: "LY"},
        {Name: "Liechtenstein", id: "LI"},
        {Name: "Lithuania", id: "LT"},
        {Name: "Luxembourg", id: "LU"},
        {Name: "Macao", id: "MO"},
        {Name: "Macedonia, The Former Yugoslav Republic of", id: "MK"},
        {Name: "Madagascar", id: "MG"},
        {Name: "Malawi", id: "MW"},
        {Name: "Malaysia", id: "MY"},
        {Name: "Maldives", id: "MV"},
        {Name: "Mali", id: "ML"},
        {Name: "Malta", id: "MT"},
        {Name: "Marshall Islands", id: "MH"},
        {Name: "Martinique", id: "MQ"},
        {Name: "Mauritania", id: "MR"},
        {Name: "Mauritius", id: "MU"},
        {Name: "Mayotte", id: "YT"},
        {Name: "Mexico", id: "MX"},
        {Name: "Micronesia, Federated States of", id: "FM"},
        {Name: "Moldova, Republic of", id: "MD"},
        {Name: "Monaco", id: "MC"},
        {Name: "Mongolia", id: "MN"},
        {Name: "Montserrat", id: "MS"},
        {Name: "Morocco", id: "MA"},
        {Name: "Mozambique", id: "MZ"},
        {Name: "Myanmar", id: "MM"},
        {Name: "Namibia", id: "NA"},
        {Name: "Nauru", id: "NR"},
        {Name: "Nepal", id: "NP"},
        {Name: "Netherlands", id: "NL"},
        {Name: "Netherlands Antilles", id: "AN"},
        {Name: "New Caledonia", id: "NC"},
        {Name: "New Zealand", id: "NZ"},
        {Name: "Nicaragua", id: "NI"},
        {Name: "Niger", id: "NE"},
        {Name: "Nigeria", id: "NG"},
        {Name: "Niue", id: "NU"},
        {Name: "Norfolk Island", id: "NF"},
        {Name: "Northern Mariana Islands", id: "MP"},
        {Name: "Norway", id: "NO"},
        {Name: "Oman", id: "OM"},
        {Name: "Pakistan", id: "PK"},
        {Name: "Palau", id: "PW"},
        {Name: "Palestinian Territory, Occupied", id: "PS"},
        {Name: "Panama", id: "PA"},
        {Name: "Papua New Guinea", id: "PG"},
        {Name: "Paraguay", id: "PY"},
        {Name: "Peru", id: "PE"},
        {Name: "Philippines", id: "PH"},
        {Name: "Pitcairn", id: "PN"},
        {Name: "Poland", id: "PL"},
        {Name: "Portugal", id: "PT"},
        {Name: "Puerto Rico", id: "PR"},
        {Name: "Qatar", id: "QA"},
        {Name: "Reunion", id: "RE"},
        {Name: "Romania", id: "RO"},
        {Name: "Russian Federation", id: "RU"},
        {Name: "RWANDA", id: "RW"},
        {Name: "Saint Helena", id: "SH"},
        {Name: "Saint Kitts and Nevis", id: "KN"},
        {Name: "Saint Lucia", id: "LC"},
        {Name: "Saint Pierre and Miquelon", id: "PM"},
        {Name: "Saint Vincent and the Grenadines", id: "VC"},
        {Name: "Samoa", id: "WS"},
        {Name: "San Marino", id: "SM"},
        {Name: "Sao Tome and Principe", id: "ST"},
        {Name: "Saudi Arabia", id: "SA"},
        {Name: "Senegal", id: "SN"},
        {Name: "Serbia and Montenegro", id: "CS"},
        {Name: "Seychelles", id: "SC"},
        {Name: "Sierra Leone", id: "SL"},
        {Name: "Singapore", id: "SG"},
        {Name: "Slovakia", id: "SK"},
        {Name: "Slovenia", id: "SI"},
        {Name: "Solomon Islands", id: "SB"},
        {Name: "Somalia", id: "SO"},
        {Name: "South Africa", id: "ZA"},
        {Name: "South Georgia and the South Sandwich Islands", id: "GS"},
        {Name: "Spain", id: "ES"},
        {Name: "Sri Lanka", id: "LK"},
        {Name: "Sudan", id: "SD"},
        {Name: "SuriName", id: "SR"},
        {Name: "Svalbard and Jan Mayen", id: "SJ"},
        {Name: "Swaziland", id: "SZ"},
        {Name: "Sweden", id: "SE"},
        {Name: "Switzerland", id: "CH"},
        {Name: "Syrian Arab Republic", id: "SY"},
        {Name: "Taiwan, Province of China", id: "TW"},
        {Name: "Tajikistan", id: "TJ"},
        {Name: "Tanzania, United Republic of", id: "TZ"},
        {Name: "Thailand", id: "TH"},
        {Name: "Timor-Leste", id: "TL"},
        {Name: "Togo", id: "TG"},
        {Name: "Tokelau", id: "TK"},
        {Name: "Tonga", id: "TO"},
        {Name: "Trinidad and Tobago", id: "TT"},
        {Name: "Tunisia", id: "TN"},
        {Name: "Turkey", id: "TR"},
        {Name: "Turkmenistan", id: "TM"},
        {Name: "Turks and Caicos Islands", id: "TC"},
        {Name: "Tuvalu", id: "TV"},
        {Name: "Uganda", id: "UG"},
        {Name: "Ukraine", id: "UA"},
        {Name: "United Arab Emirates", id: "AE"},
        {Name: "United Kingdom", id: "GB"},
        {Name: "United States", id: "US"},
        {Name: "United States Minor Outlying Islands", id: "UM"},
        {Name: "Uruguay", id: "UY"},
        {Name: "Uzbekistan", id: "UZ"},
        {Name: "Vanuatu", id: "VU"},
        {Name: "Venezuela", id: "VE"},
        {Name: "Viet Nam", id: "VN"},
        {Name: "Virgin Islands, British", id: "VG"},
        {Name: "Virgin Islands, U.S.", id: "VI"},
        {Name: "Wallis and Futuna", id: "WF"},
        {Name: "Western Sahara", id: "EH"},
        {Name: "Yemen", id: "YE"},
        {Name: "Zambia", id: "ZM"},
        {Name: "Zimbabwe", id: "ZW"}

]