//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeBulk_DataLayer.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentProd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssignmentProd()
        {
            this.ProductAssignments = new HashSet<ProductAssignment>();
        }
    
        public long AssignmentProdPID { get; set; }
        public long ProductPID { get; set; }
        public Nullable<long> Quantity { get; set; }
        public Nullable<long> ProductAssignmentPID { get; set; }
        public Nullable<long> RemQuanity { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ProductAssignment ProductAssignment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductAssignment> ProductAssignments { get; set; }
    }
}
