//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeBulk_DataLayer.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Email()
        {
            this.UserDetailEmails = new HashSet<UserDetailEmail>();
        }
    
        public long EmailPid { get; set; }
        public string ID { get; set; }
        public Nullable<long> EmailTypePID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual EmailType EmailType { get; set; }
        public virtual EmailType EmailType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserDetailEmail> UserDetailEmails { get; set; }
    }
}
