//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeBulk_DataLayer.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductState
    {
        public long ProductStatePid { get; set; }
        public string Name { get; set; }
        public Nullable<long> UserTypePId { get; set; }
        public Nullable<long> ProductTypePID { get; set; }
    
        public virtual ProductType ProductType { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
