//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeBulk_DataLayer.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductConvertView
    {
        public Nullable<long> UserPID { get; set; }
        public long ProductPID { get; set; }
        public string AssigneeUserFullName { get; set; }
        public string ProductName { get; set; }
        public string ProductCode { get; set; }
        public Nullable<long> AvailableQuantity { get; set; }
        public string AssignedUserFullName { get; set; }
        public long ProductAssignmentPID { get; set; }
    }
}
