//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeBulk_DataLayer.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductConvert
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductConvert()
        {
            this.AssignConvertRelations = new HashSet<AssignConvertRelation>();
            this.SupportConverteds = new HashSet<SupportConverted>();
        }
    
        public long ProductConvertPID { get; set; }
        public string ProductCode { get; set; }
        public Nullable<long> ConvertedUserPID { get; set; }
        public Nullable<long> OriginalOwnerPID { get; set; }
        public Nullable<decimal> AdvanceAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignConvertRelation> AssignConvertRelations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupportConverted> SupportConverteds { get; set; }
    }
}
