//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeBulk_DataLayer.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportConverted
    {
        public long SupportConvertedPID { get; set; }
        public long ProductPID { get; set; }
        public long ProductConvertPID { get; set; }
        public Nullable<long> QuanityUsed { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ProductConvert ProductConvert { get; set; }
    }
}
