//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeBulk_DataLayer.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTransac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserTransac()
        {
            this.UserTransacBrokers = new HashSet<UserTransacBroker>();
        }
    
        public long UserTransacPid { get; set; }
        public Nullable<long> FromUserPid { get; set; }
        public Nullable<long> ToUserPid { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> UserTransacDate { get; set; }
        public Nullable<long> UserTransacStatePid { get; set; }
        public Nullable<long> UserTransacTypePid { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> CreatedUserPID { get; set; }
        public Nullable<long> UpdatedUserPID { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
        public virtual UserDetail UserDetail1 { get; set; }
        public virtual UserDetail UserDetail2 { get; set; }
        public virtual UserDetail UserDetail3 { get; set; }
        public virtual UserTransacState UserTransacState { get; set; }
        public virtual UserTransacType UserTransacType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserTransacBroker> UserTransacBrokers { get; set; }
    }
}
