//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeBulk_DataLayer.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTransacBroker
    {
        public long UserTransacBrokerPID { get; set; }
        public Nullable<long> UserTransacPid { get; set; }
        public Nullable<long> buyerPid { get; set; }
        public Nullable<long> SalerPID { get; set; }
        public Nullable<bool> IsRevertedTransction { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> CreatedUserPID { get; set; }
        public Nullable<long> UpdatedUserPID { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
        public virtual UserDetail UserDetail1 { get; set; }
        public virtual UserDetail UserDetail2 { get; set; }
        public virtual UserDetail UserDetail3 { get; set; }
        public virtual UserTransac UserTransac { get; set; }
    }
}
