//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeBulk_DataLayer.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetailEmail
    {
        public long UserDetailEmailPID { get; set; }
        public Nullable<long> UserDetailPID { get; set; }
        public Nullable<long> EmailPID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Email Email { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
